apiVersion: v1
kind: Service
metadata:
  name: ayla-service-approach2
  labels:
    app: ayla-service-approach2
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: ayla-service-approach2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ayla-service-approach2
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: ayla-service-approach2
    spec:
      containers:
      - name: ayla-service-approach2
        image: ec2-54-236-75-102.compute-1.amazonaws.com:8083/admin/jslu_userservice_secured_approach2:0.0.1
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: source-code
          mountPath: /ayla/userservice
      volumes:
      - name: source-code
        emptyDir:
          medium: Memory
