apiVersion: v1
kind: Service
metadata:
  name: ayla-service
  labels:
    app: ayla-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: ayla-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ayla-service
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: ayla-service
      annotations:
        pod.boostport.com/vault-approle: ayla-service
        pod.boostport.com/vault-init-container: get-vault-token
    spec:
      containers:
      - name: ayla-service
        image: jslu/passenger-dummy:0.0.7
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
        - name: source-code
          mountPath: /ayla/dummy_prj
#        - name: dummy-prj-storage
#          mountPath: /ayla/dummy_prj
      initContainers:
      - name: get-vault-token
        image: boostport/kubernetes-vault-init
        imagePullPolicy: Always
        env:
        - name: VAULT_ROLE_ID
          value: b997790b-a129-b0a2-f3ac-35be7c0e9e41
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      volumes:
      - name: vault-token
        emptyDir: {}
      - name: source-code
        emptyDir: {}
#      - name: dummy-prj-storage
#        persistentVolumeClaim:
#          claimName: dummy-prj-pv-claim
