kind: PersistentVolume
apiVersion: v1
metadata:
  name: dummy-prj-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/joe.lu/Projects/Ayla/dummy_prj"
