kind: PersistentVolume
apiVersion: v1
metadata:
  name: dummy-prj-pv-volume
#  labels:
#    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv0001
